# Generated by Django 5.1.5 on 2025-04-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0002_alter_hotels_name'),
        ('user', '0004_hotelstaff_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='assigned_staff',
            field=models.ManyToManyField(blank=True, related_name='assigned_hotels', to='user.hotelstaff'),
        ),
        migrations.AddConstraint(
            model_name='hotels',
            constraint=models.UniqueConstraint(fields=('name', 'owner', 'state', 'country', 'location'), name='unique_hotel_constraint'),
        ),
    ]
