# Generated by Django 5.1.5 on 2025-04-03 16:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0003_hotels_assigned_staff_hotels_unique_hotel_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='krishna.rooms'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='status',
            field=models.CharField(choices=[('1', 'available'), ('2', 'not available')], default='1', max_length=1),
        ),
    ]
