# Generated by Django 5.1.5 on 2025-04-04 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0004_alter_reservation_room_alter_rooms_discount_and_more'),
        ('user', '0004_hotelstaff_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_hotels', to='user.hotelstaff'),
        ),
    ]
