# Generated by Django 5.2 on 2025-04-18 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0005_hotels_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='parking_area',
        ),
    ]
