# Generated by Django 5.2 on 2025-04-28 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0006_remove_rooms_parking_area'),
        ('user', '0013_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_hotels', to='user.hotelstaff'),
        ),
    ]
