# Generated by Django 5.2 on 2025-05-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0007_alter_hotels_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='description_map',
            field=models.TextField(blank=True, help_text='Detailed description of the room', null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='embedded_map_link',
            field=models.TextField(blank=True, help_text='Embed map link (iframe URL). Will be shown in fixed size on frontend.', null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='heading_map',
            field=models.CharField(blank=True, help_text='Short heading for the room', max_length=100, null=True),
        ),
    ]
