# Generated by Django 5.2 on 2025-05-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0008_rooms_description_map_rooms_embedded_map_link_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotels',
            options={'ordering': ['-rank', 'name']},
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='description_map',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='embedded_map_link',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='heading_map',
        ),
        migrations.AddField(
            model_name='hotels',
            name='description_map',
            field=models.TextField(blank=True, help_text='Detailed description of the room', null=True),
        ),
        migrations.AddField(
            model_name='hotels',
            name='embedded_map_link',
            field=models.TextField(blank=True, help_text='Embed map link (iframe URL). Will be shown in fixed size on frontend.', null=True),
        ),
        migrations.AddField(
            model_name='hotels',
            name='heading_map',
            field=models.CharField(blank=True, help_text='Short heading for the room', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotels',
            name='rank',
            field=models.PositiveIntegerField(default=0, help_text='Higher rank means higher priority in listings'),
        ),
    ]
