# Generated by Django 5.2 on 2025-05-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0010_hotels_image_1_hotels_image_2_hotels_image_3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotels',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='image_4',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='image_5',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='image_6',
        ),
        migrations.AlterField(
            model_name='hotels',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
