# Generated by Django 5.2 on 2025-05-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0011_remove_hotels_image_1_remove_hotels_image_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='image_1',
            field=models.ImageField(blank=True, help_text='First hotel image', null=True, upload_to='hotel_images/'),
        ),
        migrations.AddField(
            model_name='hotels',
            name='image_2',
            field=models.ImageField(blank=True, help_text='Second hotel image', null=True, upload_to='hotel_images/'),
        ),
        migrations.AddField(
            model_name='hotels',
            name='image_3',
            field=models.ImageField(blank=True, help_text='Third hotel image', null=True, upload_to='hotel_images/'),
        ),
        migrations.AddField(
            model_name='hotels',
            name='image_4',
            field=models.ImageField(blank=True, help_text='Fourth hotel image', null=True, upload_to='hotel_images/'),
        ),
        migrations.AddField(
            model_name='hotels',
            name='image_5',
            field=models.ImageField(blank=True, help_text='Fifth hotel image', null=True, upload_to='hotel_images/'),
        ),
        migrations.AddField(
            model_name='hotels',
            name='image_6',
            field=models.ImageField(blank=True, help_text='Sixth hotel image', null=True, upload_to='hotel_images/'),
        ),
    ]
