# Generated by Django 5.2 on 2025-05-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0012_hotels_image_1_hotels_image_2_hotels_image_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='name',
            field=models.CharField(default='tiranga', max_length=130),
        ),
    ]
