# Generated by Django 5.2.1 on 2025-05-08 10:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0013_alter_hotels_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='booking_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
