# Generated by Django 5.2.1 on 2025-05-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0014_reservation_booking_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('past', 'Past'), ('current', 'Current'), ('future', 'Future')], default='future', max_length=20),
        ),
    ]
