# Generated by Django 5.2.1 on 2025-05-12 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0015_reservation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='status',
        ),
    ]
