# Generated by Django 5.2.1 on 2025-05-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0016_remove_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='hotel_type',
            field=models.CharField(choices=[('hotel_restaurant', 'Hotel/Restaurant'), ('dormitory', 'Dormitory'), ('math_dharmashala', 'Math/Dharmashala'), ('other', 'Other')], default='hotel_restaurant', help_text='Type of the hotel or accommodation', max_length=20),
        ),
        migrations.AddField(
            model_name='hotels',
            name='other_heading',
            field=models.CharField(blank=True, help_text="Custom heading if hotel type is 'Other'", max_length=100, null=True),
        ),
    ]
