# Generated by Django 5.2.1 on 2025-05-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0018_alter_hotels_hotel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='hotel_type',
            field=models.CharField(choices=[('hotel_restaurant', 'Hotel/Restaurant'), ('dormitory', 'Dormitory'), ('math_dharmashala', 'Math/Dharmashala'), ('other', 'Other')], default='hotel / restaurant', help_text='Type of the hotel or accommodation', max_length=20),
        ),
    ]
