# Generated by Django 5.2.1 on 2025-05-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0019_alter_hotels_hotel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=12.0, help_text='GST rate in percentage (e.g., 12 for 12%)', max_digits=5),
        ),
    ]
