# Generated by Django 4.0.3 on 2025-06-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0021_reservation_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='cancellation_time',
            new_name='cancellation_date',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='booking_id',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
