# Generated by Django 4.0.3 on 2025-06-10 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0022_rename_cancellation_time_reservation_cancellation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='cancellation_date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='cancellation_reason',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='is_cancelled',
        ),
    ]
