# Generated by Django 5.2.1 on 2025-06-13 09:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0026_reservation_base_price_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='extra_capacity',
            field=models.IntegerField(default=0, help_text='Extra capacity beyond base (e.g., with extra beds)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='capacity',
            field=models.IntegerField(help_text='Base capacity of the room', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
