# Generated by Django 5.2.1 on 2025-06-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0028_alter_reservation_number_of_guests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='capacity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='extra_capacity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='extra_person_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
