# Generated by Django 5.2.1 on 2025-06-23 13:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0030_alter_reservation_number_of_guests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='number_of_guests',
            field=models.PositiveIntegerField(default=1, help_text='Total number of guests for the reservation', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='krishna.rooms'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='capacity',
            field=models.IntegerField(help_text='Base capacity of the room', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='extra_capacity',
            field=models.IntegerField(default=0, help_text='Extra capacity beyond base (e.g., with extra beds)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='extra_person_charges',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Charges for extra person', max_digits=6, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
