# Generated by Django 5.2.1 on 2025-06-27 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0031_alter_reservation_number_of_guests_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('aadhar_front', models.ImageField(upload_to='documents/aadhar_front/')),
                ('aadhar_back', models.ImageField(upload_to='documents/aadhar_back/')),
                ('pan_card', models.ImageField(upload_to='documents/pan_card/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='krishna.reservation')),
            ],
        ),
    ]
