# Generated by Django 5.2.1 on 2025-06-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0032_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='customer_gst_number',
            field=models.CharField(blank=True, help_text="Customer's GST number (required if including GST)", max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='include_gst',
            field=models.BooleanField(default=False, help_text='Whether to include GST in the bill'),
        ),
    ]
