# Generated by Django 5.2.1 on 2025-06-30 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0033_reservation_customer_gst_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='customer_gst_number',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='include_gst',
        ),
    ]
