# Generated by Django 5.2.1 on 2025-06-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0034_remove_reservation_customer_gst_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='gst_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='include_gst',
            field=models.BooleanField(default=False),
        ),
    ]
