# Generated by Django 5.2.1 on 2025-06-30 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0035_reservation_gst_number_reservation_include_gst'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='gst_number',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='include_gst',
        ),
    ]
