# Generated by Django 5.2.1 on 2025-07-01 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0036_remove_reservation_gst_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='apply_gst',
            field=models.BooleanField(default=False, help_text='Whether GST is applied to this reservation'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='gst_number',
            field=models.CharField(blank=True, help_text='GST number if GST is applied', max_length=15, null=True),
        ),
    ]
