# Generated by Django 5.2.1 on 2025-07-01 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0037_reservation_apply_gst_reservation_gst_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='apply_gst',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='gst_number',
        ),
    ]
