# Generated by Django 5.2.1 on 2025-07-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0038_remove_reservation_apply_gst_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='apply_gst',
            field=models.BooleanField(default=False, help_text='Whether to apply GST to this reservation'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='gst_number',
            field=models.CharField(blank=True, help_text='GST number if applicable', max_length=15, null=True),
        ),
    ]
