# Generated by Django 5.2.1 on 2025-07-01 11:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0039_reservation_apply_gst_reservation_gst_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='gst_number',
            field=models.CharField(blank=True, help_text='GST number if applicable', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='GST number must be in the format: 2 digits, 5 alphanumeric, 4 digits, 1 alphanumeric, 1 digit, 1 alphanumeric (e.g., 12ABCDE1234F5GH).', regex='^\\d{2}[A-Z0-9]{5}\\d{4}[A-Z0-9]{1}\\d{1}[A-Z0-9]{1}$')]),
        ),
    ]
