# Generated by Django 5.1.5 on 2025-03-26 13:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='advertisements/')),
                ('order', models.PositiveIntegerField()),
                ('is_google_adsense', models.BooleanField(default=False)),
                ('google_adsense_code', models.TextField(blank=True, help_text='Paste Google AdSense code here', null=True)),
                ('site_link', models.URLField(blank=True, help_text='Enter website URL for manual ads', null=True)),
                ('position', models.CharField(choices=[('upper-menu', 'Upper menu'), ('below-menu', 'Below menu'), ('left-side-of-page', 'Left side of the page'), ('right-side-of-page', 'Right side of the page'), ('below-page', 'Below the page'), ('below-footer', 'Below footer')], default='upper-menu', max_length=50)),
                ('status', models.CharField(choices=[('enable', 'Enable'), ('disable', 'Disable')], default='enable', max_length=10)),
            ],
            options={
                'verbose_name': 'Advertisement',
                'verbose_name_plural': 'Advertisements',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('heading', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True, null=True)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='myapp.comment')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myapp.image')),
            ],
        ),
    ]
