# Generated by Django 5.2.1 on 2025-05-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_advertisement_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='countdown_duration',
            field=models.PositiveIntegerField(default=5, help_text='Countdown duration in seconds (if show_countdown is enabled)'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='display_frequency',
            field=models.CharField(choices=[('once', 'Show once per session'), ('repeat', 'Repeat every 10 seconds after closing'), ('every_page', 'Show on every page load')], default='once', help_text='How often should this ad be displayed?', max_length=20),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='show_countdown',
            field=models.BooleanField(default=True, help_text='Show countdown timer before user can close ad'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='video',
            field=models.FileField(blank=True, help_text='Upload video file for video ads', null=True, upload_to='advertisements/videos/'),
        ),
    ]
