# Generated by Django 5.2.1 on 2025-05-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_advertisement_countdown_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='display_frequency',
            field=models.CharField(choices=[('once', 'Show once per session'), ('repeat', 'Repeat every 10 seconds after closing')], default='once', help_text='How often should this ad be displayed?', max_length=20),
        ),
    ]
