# Generated by Django 5.2.1 on 2025-05-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_advertisement_display_frequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='show_countdown',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='countdown_mode',
            field=models.CharField(choices=[('off', 'No countdown timer'), ('custom', 'Custom countdown timer')], default='off', help_text='Should a countdown timer be shown before the ad can be closed?', max_length=20),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='repeat_interval',
            field=models.PositiveIntegerField(default=20, help_text="Time in seconds before the ad repeats (applies only if display_frequency is 'repeat')"),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='countdown_duration',
            field=models.PositiveIntegerField(default=10, help_text="Countdown duration in seconds (applies only if countdown_mode is 'custom')"),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='display_frequency',
            field=models.CharField(choices=[('show_once', 'Show once per session'), ('repeat', 'Repeat after interval')], default='show_once', help_text='How often should this ad be displayed?', max_length=20),
        ),
    ]
