# Generated by Django 5.1.5 on 2025-04-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelstaff',
            name='country',
            field=models.CharField(default='india', max_length=50),
        ),
        migrations.AddField(
            model_name='hotelstaff',
            name='hotel_name',
            field=models.CharField(default='krishna', max_length=30),
        ),
        migrations.AddField(
            model_name='hotelstaff',
            name='location',
            field=models.CharField(default='pandharpur', max_length=50),
        ),
        migrations.AddField(
            model_name='hotelstaff',
            name='state',
            field=models.CharField(default='maharashtra', max_length=50),
        ),
    ]
