# Generated by Django 5.1.5 on 2025-04-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_hotelstaff_country_hotelstaff_hotel_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelstaff',
            name='userf_name',
            field=models.CharField(default='krishna', max_length=30),
        ),
    ]
