# Generated by Django 5.1.5 on 2025-04-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_hotelstaff_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelstaff',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
