# Generated by Django 5.1.5 on 2025-04-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_hotelstaff_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelstaff',
            name='staff_id',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
