# Generated by Django 5.1.5 on 2025-04-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_maintainer_is_authority_to_manage_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_authority_to_manage_hotel',
            field=models.BooleanField(default=False),
        ),
    ]
