# Generated by Django 5.2 on 2025-04-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0007_alter_hotels_created_by'),
        ('user', '0013_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_hotels',
            field=models.ManyToManyField(blank=True, related_name='assigned_staff_hotels', to='krishna.hotels'),
        ),
    ]
